speakers:
  0:
    x: 1.0
    y: 1.0
    z: 1.0
    directness: 1.0
  1:
    x: 2.0
    y: 5.0
    z: 2.0
    directness: 1.0
  2:
    x: 3.0
    y: 15.0
    z: 3.0
    directness: 1.0
  3:
    x: 4.0
    y: 5.0
    z: 4.0
    directness: 1.0
  4:
    x: 5.0
    y: 2.0
    z: 44.0
    directness: 1.0
  5:
    x: 6.0
    y: 25.0
    z: 33.0
    directness: 1.0
  6:
    x: 7.0
    y: 11.0
    z: 22.0
    directness: 1.0
  7:
    x: 8.0
    y: 8.0
    z: 11.0
    directness: 1.0

outputs:
  0:
    x: 1.0
    y: 0.0
    z: 0.0
    directness: 1.0
  1:
    x: 8.0
    y: 0.0
    z: 0.0
    directness: 1.0
